name: Flavio – Syncope CI (selected modules)

on:
  push:
    branches: [ main, master ]
    paths:
      - 'syncope/**'
      - '.github/workflows/flavio-syncope-ci.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'syncope/**'
  workflow_dispatch:

# Tutti i comandi Maven girano dentro alla cartella syncope/
defaults:
  run:
    working-directory: syncope

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      # Evita problemi JPMS con Java 21 + Surefire
      MAVEN_ARGS: "-DtrimStackTrace=false -DfailIfNoTests=false -Dmaven.test.failure.ignore=false"
      SKIP_CHECKS: "-Dspotbugs.skip=true -Dcheckstyle.skip=true -Denforcer.skip=true"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Tool versions
        run: |
          mvn -v
          java -version

      # Compila SOLO i moduli dei tuoi test + le dipendenze necessarie
      - name: Build (compile only needed modules)
        run: |
          mvn -B -ntp -q ${SKIP_CHECKS} \
            -pl "core/idrepo/logic,core/spring" -am \
            -DskipTests=true \
            clean compile

      # Test con Surefire (JUnit 5). Se l'engine non è trovato, qui lo vediamo chiaramente.
      - name: Test (Surefire)
        run: |
          mvn -B -ntp ${SKIP_CHECKS} ${MAVEN_ARGS} \
            -pl "core/idrepo/logic,core/spring" -am \
            -DskipITs=true \
            -Dsurefire.useModulePath=false \
            -Dsurefire.trimStackTrace=false \
            test

      # Report JaCoCo se già configurato nei POM
      - name: Test coverage (JaCoCo if configured)
        run: |
          mvn -B -ntp ${SKIP_CHECKS} ${MAVEN_ARGS} \
            -pl "core/idrepo/logic,core/spring" -am \
            -DskipITs=true \
            jacoco:report || true

      # Carica SEMPRE i report Surefire
      - name: Upload Surefire reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: |
            **/target/surefire-reports/*
          if-no-files-found: warn

      - name: Upload JaCoCo reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-reports
          path: |
            **/target/site/jacoco/*
          if-no-files-found: warn
